---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
namespace: renovate
resources:
  - manifests/cronjob.yaml
  - manifests/externalsecret.yaml
  - manifests/pvc.yaml
components:
  - ../../components/namespace
configMapGenerator:
  - name: renovate-config
    files:
      - config.js=manifests/config.js
    namespace: renovate
generatorOptions:
  disableNameSuffixHash: true
