---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hivemq
  namespace: hivemq
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: gateway
  hostnames:
    - hivemq.mgmt.sholdee.net
  rules:
    - backendRefs:
        - name: hivemq-hivemq-platform-cc-8080
          namespace: hivemq
          port: 8080
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: hivemq-lb-policy
  namespace: hivemq
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hivemq
  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: SourceIP
