---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hivemq-platform
  namespace: hivemq
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: hivemq-platform
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: hivemq-platform
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: hass
      toPorts:
        - ports:
            - port: "1883"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
      toPorts:
        - ports:
            - port: "8883"
              protocol: TCP
            - port: "8080"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "9399"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: /metrics
