---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
components:
  - ../../components/namespace
resources:
  - manifests/namespace.yaml
  - manifests/podmonitor.yaml
helmCharts:
  - name: gateway-helm
    repo: oci://mirror.gcr.io/envoyproxy
    version: 1.7.0
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
    valuesFile: manifests/values.yaml
