---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-http
  namespace: adguard
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: default
    sectionName: http
  hostnames:
  - adguard.mgmt.sholdee.net
  rules:
    - filters:
        - requestRedirect:
            scheme: https
            statusCode: 301
          type: RequestRedirect
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-https
  namespace: adguard
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: default
      sectionName: https
  hostnames:
    - adguard.mgmt.sholdee.net
  rules:
    - backendRefs:
        - name: adguard-http
          port: 80
      sessionPersistence:
        sessionName: route
        type: Cookie
