---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp
components:
  - ../../components/namespace
resources:
  - manifests/httproute.yaml
  - manifests/namespace.yaml
  - manifests/secret.yaml
helmCharts:
  - name: headlamp
    repo: https://kubernetes-sigs.github.io/headlamp/
    version: 0.39.0
    releaseName: headlamp
    namespace: headlamp
