---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels:
      app: longhorn-ui
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
      toPorts:
        - ports:
            - port: "8000"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backing-image-data-source
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels:
      longhorn.io/component: backing-image-data-source
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: longhorn-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: instance-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: backing-image-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: backing-image-data-source
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backing-image-manager
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels:
      longhorn.io/component: backing-image-manager
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: longhorn-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: instance-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: backing-image-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: backing-image-data-source
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: instance-manager
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels:
      longhorn.io/component: instance-manager
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: longhorn-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: instance-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: backing-image-manager
    - fromEndpoints:
        - matchLabels:
            longhorn.io/component: backing-image-data-source
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: longhorn-manager
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels:
      app: longhorn-manager
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: longhorn-manager
    - fromEndpoints:
        - matchLabels:
            app: longhorn-ui
    - fromEndpoints:
        - matchLabels:
            app: longhorn-csi-plugin
    - fromEndpoints:
        - matchLabels:
            longhorn.io/managed-by: longhorn-manager
          matchExpressions:
            - key: recurring-job.longhorn.io
              operator: Exists
    - fromEndpoints:
        - matchExpressions:
            - key: longhorn.io/job-task
              operator: Exists
    - fromEndpoints:
        - matchLabels:
            app: longhorn-driver-deployer
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "9500"
          rules:
            http:
              - method: "GET"
                path: "/metrics"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: longhorn-recovery-backend
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels:
      longhorn.io/recovery-backend: longhorn-recovery-backend
  ingress:
    - toPorts:
        - ports:
            - port: "9503"
              protocol: TCP
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: longhorn-admission-webhook
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels:
      longhorn.io/admission-webhook: longhorn-admission-webhook
  ingress:
    - toPorts:
        - ports:
            - port: "9502"
              protocol: TCP
