---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmgr
  namespace: monitoring
spec:
  parentRefs:
  - name: mgmt-gateway
    namespace: gateway
  hostnames:
  - alertmgr.mgmt.sholdee.net
  rules:
  - backendRefs:
    - name: kube-prometheus-stack-alertmanager
      namespace: monitoring
      port: 9093
