---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-cert
  namespace: unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gateway
  target:
    name: unifi-cert
    template:
      engineVersion: v2
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: mgmt-wildcard
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: mgmt-wildcard
        property: tls.key
