---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: unifi
  namespace: unifi
spec:
  endpointSelector:
    matchLabels:
      app: unifi
  ingress:
    - fromEntities:
        - all
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: unifi-landing
      toPorts:
        - ports:
            - port: "8843"
              protocol: TCP
