---
apiVersion: v1
kind: Service
metadata:
  name: unifi-lb
  namespace: unifi
spec:
  selector:
    app: unifi
  ports:
  - protocol: TCP
    port: 8080
    name: deviceappcomms
  type: LoadBalancer
  loadBalancerIP: 192.168.77.21
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-ui
  namespace: unifi
spec:
  selector:
    app: unifi
  ports:
  - protocol: TCP
    port: 8443
    name: gui
  type: ClusterIP
