---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    name: argocd-server-tls
    template:
      engineVersion: v2
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: external-wildcard
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: external-wildcard
        property: tls.key
