---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd-server
  namespace: argocd
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: argocd-server
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/component: proxy
            app.kubernetes.io/managed-by: envoy-gateway
            gateway.envoyproxy.io/owning-gateway-name: exernal-gateway
      toPorts:
        - ports:
            - port: "8080"
