---
apiVersion: v1
stringData:
  name: k3s
  project: k3s
  type: git
  url: https://github.com/sholdee/home-ops
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: home-ops
type: Opaque
---
apiVersion: v1
stringData:
  name: longhorn
  project: k3s
  type: helm
  url: https://charts.longhorn.io
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: longhorn
type: Opaque
---
apiVersion: v1
stringData:
  name: cilium
  project: k3s
  type: helm
  url: https://helm.cilium.io/
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: cilium
type: Opaque
---
apiVersion: v1
stringData:
  name: stakater
  project: k3s
  type: helm
  url: https://stakater.github.io/stakater-charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: reloader
type: Opaque
---
apiVersion: v1
stringData:
  name: backube
  project: k3s
  type: helm
  url: https://backube.github.io/helm-charts/
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: volsync
type: Opaque
---
apiVersion: v1
stringData:
  name: headlamp
  project: k3s
  type: helm
  url: https://kubernetes-sigs.github.io/headlamp/
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: headlamp
type: Opaque
