apiVersion: v1
stringData:
  name: k3s
  project: k3s
  type: git
  url: https://github.com/sholdee/home-ops
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-home-ops
type: Opaque
---
apiVersion: v1
stringData:
  name: argocd
  project: k3s
  type: helm
  url: https://argoproj.github.io/argo-helm
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-argocd
type: Opaque
---
apiVersion: v1
stringData:
  name: cert-manager
  project: k3s
  type: helm
  url: https://charts.jetstack.io
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-cert-manager
type: Opaque
---
apiVersion: v1
stringData:
  name: ingress-nginx
  project: k3s
  type: helm
  url: https://kubernetes.github.io/ingress-nginx
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-ingress-nginx
type: Opaque
---
apiVersion: v1
stringData:
  name: longhorn
  project: k3s
  type: helm
  url: https://charts.longhorn.io
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-longhorn
type: Opaque
---
apiVersion: v1
stringData:
  name: kubernetes-dashboard
  project: k3s
  type: helm
  url: https://kubernetes.github.io/dashboard
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-kubernetes-dashboard
type: Opaque
---
apiVersion: v1
stringData:
  name: vmware-tanzu
  project: k3s
  type: helm
  url: https://vmware-tanzu.github.io/helm-charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-velero
type: Opaque
---
apiVersion: v1
stringData:
  name: cilium
  project: k3s
  type: helm
  url: https://helm.cilium.io/
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-cilium
type: Opaque
---
apiVersion: v1
stringData:
  name: prometheus-community
  project: k3s
  type: helm
  url: https://prometheus-community.github.io/helm-charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-prometheus-community
type: Opaque
---
apiVersion: v1
stringData:
  name: stakater
  project: k3s
  type: helm
  url: https://stakater.github.io/stakater-charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-stakater-reloader
type: Opaque
---
apiVersion: v1
stringData:
  name: kubereboot
  project: k3s
  type: helm
  url: https://kubereboot.github.io/charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-kubereboot
type: Opaque
---
apiVersion: v1
stringData:
  name: cnpg
  project: k3s
  type: helm
  url: https://cloudnative-pg.github.io/charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-cnpg
type: Opaque
---
apiVersion: v1
stringData:
  name: mongodb
  project: k3s
  type: helm
  url: https://mongodb.github.io/helm-charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-mongodb
type: Opaque
---
apiVersion: v1
stringData:
  name: 1password
  project: k3s
  type: helm
  url: https://1password.github.io/connect-helm-charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-1password
type: Opaque
---
apiVersion: v1
stringData:
  name: external-secrets
  project: k3s
  type: helm
  url: https://charts.external-secrets.io
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-external-secrets
type: Opaque
---
apiVersion: v1
stringData:
  name: confluent
  project: k3s
  type: helm
  url: https://packages.confluent.io/helm
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-confluent
type: Opaque
---
apiVersion: v1
stringData:
  name: vernemq
  project: k3s
  type: helm
  url: https://vernemq.github.io/docker-vernemq
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-vernemq
type: Opaque
---
apiVersion: v1
stringData:
  name: backube
  project: k3s
  type: helm
  url: https://backube.github.io/helm-charts/
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-backube
type: Opaque
---
apiVersion: v1
stringData:
  name: external-dns
  project: k3s
  type: helm
  url: https://kubernetes-sigs.github.io/external-dns/
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-external-dns
type: Opaque
---
apiVersion: v1
stringData:
  name: kgateway
  project: k3s
  type: helm
  url: cr.kgateway.dev/kgateway-dev/charts
  enableOCI: "true"
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-kgateway
type: Opaque
---
apiVersion: v1
stringData:
  name: istio
  project: k3s
  type: helm
  url: https://istio-release.storage.googleapis.com/charts
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-istio
type: Opaque
