---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
namespace: hass
components:
  - ../../components/namespace
resources:
  - appdaemon
  - codeserver
  - hass
  - hass-db
  - mqtt-venstar-bridge
  - vernemq
  - zwave
