---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-gateway-proxy-monitoring
  namespace: envoy-gateway-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/component: proxy
  namespaceSelector:
    any: true
  jobLabel: envoy-proxy-metrics
  podMetricsEndpoints:
    - path: /stats/prometheus
      port: metrics
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
spec:
  selector:
    matchLabels:
      control-plane: envoy-gateway
  namespaceSelector:
    any: true
  jobLabel: envoy-gateway
  endpoints:
    - port: metrics
      path: /metrics
