---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
namespace: system-upgrade
components:
  - ../../components/namespace
resources:
  - https://raw.githubusercontent.com/rancher/system-upgrade-controller/refs/tags/v0.17.0/pkg/crds/yaml/generated/upgrade.cattle.io_plans.yaml
  - manifests/controller.yaml
  - manifests/plan.yaml
