---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
namespace: gateway
components:
  - ../../components/namespace
resources:
  - manifests/mgmt-gateway.yaml
  - manifests/external-gateway.yaml
  - manifests/guest-gateway.yaml
  - manifests/envoy-gateway.yaml
  - manifests/envoy-gatewayclass.yaml
