---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
namespace: portainer
resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/httproute.yaml
  - manifests/netpol.yaml
components:
  - ../../components/volsync
  - ../../components/volsync/b2
  - ../../components/namespace
patches:
  - target:
      kind: ReplicationSource
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: portainer
      - op: replace
        path: /spec/sourcePVC
        value: portainer-pvc
      - op: replace
        path: /spec/restic/repository
        value: portainer-volsync-b2
  - target:
      kind: ReplicationDestination
      name: app-bootstrap
    patch: |-
      - op: replace
        path: /metadata/name
        value: portainer-bootstrap
      - op: replace
        path: /spec/restic/repository
        value: portainer-volsync-b2
  - target:
      kind: ExternalSecret
      name: app-volsync-b2
    patch: |-
      - op: replace
        path: /metadata/name
        value: portainer-volsync-b2
      - op: replace
        path: /spec/target/name
        value: portainer-volsync-b2
      - op: replace
        path: /spec/target/template/data/RESTIC_REPOSITORY
        value: "s3:s3.us-west-002.backblazeb2.com/sholdee-volsync/portainer"
  - target:
      kind: PersistentVolumeClaim
      name: app-pvc
    patch: |-
      - op: replace
        path: /metadata/name
        value: portainer-pvc
      - op: replace
        path: /spec/dataSourceRef/name
        value: portainer-bootstrap
