---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
resources:
  - manifests/CiliumBGPClusterConfig.yaml
  - manifests/hubble/externalsecret.yaml
  - manifests/hubble/httproute.yaml
  - manifests/hubble/netpol.yaml
