---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gravity
  namespace: gravity
spec:
  endpointSelector:
    matchLabels:
      app: gravity
  ingress:
    - fromEntities:
        - all
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
      toPorts:
        - ports:
            - port: "8008"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: external-dns
            app.kubernetes.io/name: external-dns
      toPorts:
        - ports:
            - port: "8008"
              protocol: TCP
          rules:
            http: [{}]
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: etcd
  namespace: gravity
spec:
  endpointSelector:
    matchLabels:
      app: etcd
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: gravity
      toPorts:
        - ports:
            - port: "2379"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: etcd
      toPorts:
        - ports:
            - port: "2380"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "2381"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: /metrics
